---
title: "Analysis and Documentation"
author: "Jonny Nelson"
date: "25/11/2021"
output: html_document
---

# Loading in the required packages

```{r}
library(tidyverse)

library(here)

library(readxl)

library(janitor)

library(assertr)
```

# Read in the seabird_data_clean

```{r}

seabird_clean <- read_csv(here("clean_data/seabird_data_clean.csv"))

```
# 1. Which bird has the most indivdual sightings?

```{r}

seabird_data %>%
  filter(count == 1) %>%
  group_by(species_common_name) %>%
  summarise(number_of_individual_sightings = sum(count)) %>%
  arrange(desc(number_of_individual_sightings)) 

# Wandering albatross

```

# 2. Which bird has the highest total count

```{r}

seabird_data %>%
  group_by(species_common_name) %>%
  summarise(number_of_sightings = sum(count)) %>%
  arrange(desc(number_of_sightings)) %>%
  head(1,)
  
# Short-tailed shearwater has the highest total sightings.

```

# 3. Which bird had the highest total count above a latitude of -30?

```{r}

seabird_data %>%
  filter(latitude > -30) %>%
  group_by(species_common_name) %>%
  summarise(number_of_sightings = sum(count)) %>%
  arrange(desc(number_of_sightings)) %>%
  head(1,)

# Wedge-tailed shearwater has the highest count above latitude of -30

```

# 4. How many different types of birds were only ever seen in groups of 1?

```{r}

cleaning_script_q4 <- function(bird_data_by_record_id){
  
  bird_data_by_record_id %>%
  clean_names() %>%
  select(record,
         record_id,
         species_common_name_taxon_age_sex_plumage_phase,
         count) %>%
   mutate(species_common_name = 
      str_replace_all(string = species_common_name_taxon_age_sex_plumage_phase,
                      pattern = "sensu.*$|[A-Z]{2,}.*$",
                      replacement = "")) %>%
    mutate(across(where(is.character), str_trim)) %>%
    # mutate(count = ifelse(is.na(count), 1, count)) %>%
    select(-species_common_name_taxon_age_sex_plumage_phase) 
}


# the cleaning script was ran again for q4 to give the data.


clean_bird_data_q4 <- cleaning_script_q4(bird_data_by_record_id)


# The data.frames were joined again to form a new one.


seabird_data_q4 <- left_join(clean_bird_data_q4, clean_ship_data, "record_id")

# Forming two tables and then performing an anti-join

groups_of_one <- seabird_data_q4 %>%
  select(species_common_name, count) %>%
  drop_na(count) %>%
  filter(count == 1) %>%
  group_by(species_common_name) %>%
  summarise(sum(count))

groups_of_greater_than_one <- seabird_data_q4 %>%
  select(species_common_name, count) %>%
  drop_na(count) %>%
  filter(count > 1) %>%
  group_by(species_common_name) %>%
  summarise(sum(count))

q4_answer <- anti_join(groups_of_one, groups_of_greater_than_one, by = "species_common_name")

# See global environment for the answer, 23 species.


# Testing that the number of species brought back are correct in the original clean_bird_data

  
ccc <- clean_bird_data %>%
  select(species_common_name, count) %>%
  filter(species_common_name == "White-tailed tropicbird")
  
  
```

# 5. How many penguins were seen?

```{r}

seabird_data %>%
  filter(grepl('penguin', species_common_name)) %>%
  group_by(species_common_name) %>%
  summarise(number_of_pingos_seen = sum(count)) %>%
  arrange(desc(number_of_pingos_seen)) %>%
  mutate(total_no_pingos = sum(number_of_pingos_seen))

# Below shows the number of penguins shown per species and also the total number of penguins observed.
  

```





# Question 4 different attempts made (junk code)

```{r}
 seabird_data %>%
   select(species_common_name, count) %>%
   filter(count != 1) %>%
   group_by(species_common_name)

 function if_else statement required

 if count == 1, == TRUE
 if count >= 1, == FALSE
 if species_common_name has only TRUE = allow
 if species_common_name has TRUE and FALSE = dont allow

 species_of_1_group_only <- function(seabird_data, count) {

   if(count == 1 & count !> 1) {
     return(species_common_name)}

 }

# if count is not equal to 1 set to 0
 
species_observed_in_only_groups_of_one(seabird_data, count)

seabird_data$count <- ifelse(seabird_data$count != 1,
                              0,
                              seabird_data$count)

# Needed to remove the mutate NA <- 1 out of the cleaning script and form a new script.

test <- seabird_data_q4 %>%
  select(species_common_name, count) %>%
  filter(count > 1) %>%
  group_by(species_common_name) %>%
  summarise() %>%
  mutate(number_of_species = nrow(species_common_name))

# nrow

# group_by
# summarise max count
# filter where = 1 



# Need to remove the convert NA = 1 function in cleaning script and then rejoin the tables and then run the code]=.

q4_work <- seabird_data_q4 %>%
  select(species_common_name,count) %>%
  drop_na(count) %>%
  mutate(groups_observed = case_when(
    count == 1 & !(count >= 1) ~ "only one",
    TRUE ~ "greater than one"
  )) 
  
  
  # mutate(groups_observed = 
  #          if_else(count > 1, "groups > 1", "groups = 1")) %>%
  
```


