---
title: "Analysis and Questions"
author: "Jonny Nelson"
date: "24/11/2021"
output: html_document
---

# Loading in packages

```{r}
library(tidyverse)
```


# Loading in the clean_data

```{r}

candy_clean <- read_csv(here("clean_data/candy_clean.csv"))

```

# Analysis Questions


```{r}

# 1. What is the total number of candy ratings given across the three years. (Number of candy ratings, not the number of raters. Don’t count missing values)

candy_clean %>%
  select(entry, rating) %>%
  drop_na(rating) %>%
  summarise(count = n())


```

```{r}

# 2. What was the average age of people who are going out trick or treating?

candy_clean %>%
  select(entry, age, going_out) %>%
  filter(going_out == "Yes") %>%
  drop_na(age) %>%
  summarise(average_age_of_people = mean(age))

```


```{r}

# 2. What was the average age of people who are going out trick or treating?

candy_clean %>%
  select(entry, age, going_out) %>%
  filter(going_out == "No") %>%
  drop_na(age) %>%
  summarise(average_age_of_people = mean(age))

```

```{r}

# 4. For each of joy, despair and meh, which candy bar revived the most of these ratings?

# Can use the function unique() to find all values in rating

unique(candy_clean$rating)

# JOY

candy_clean %>%
  select(entry, rating, candy_name) %>%
  filter(rating == "JOY") %>%
  drop_na(rating) %>%
  group_by(candy_name, rating) %>%
  count(rating) %>%
  arrange(desc(n))

# "any_full_sized_candy_bar" and then "reese_s_peanut_butter_cups" returned the most joy ratings


# DESPAIR

candy_clean %>%
  select(entry, rating, candy_name) %>%
  filter(rating == "DESPAIR") %>%
  drop_na(rating) %>%
  group_by(candy_name, rating) %>%
  count(rating) %>%
  arrange(desc(n))

# "gum_from_baseball_cards" returned the most despair ratings


# MEH

candy_clean %>%
  select(entry, rating, candy_name) %>%
  filter(rating == "MEH") %>%
  drop_na(rating) %>%
  group_by(candy_name, rating) %>%
  count(rating) %>%
  arrange(desc(n))

# "lollipops" returned the most MEH ratings

```

```{r}

# 5. How many people rated Starburst as despair?

candy_clean %>%
  select(entry, rating, candy_name) %>%
  filter(rating == "DESPAIR" & candy_name == "starburst") %>%
  group_by(candy_name) %>%
  summarise(count = n())

# 1990 people rated starburst as "DESPAIR" over 3 years

```

```{r}

# For the next three questions, count despair as -1, joy as +1, and meh as 0.

recoded_candy_clean <- candy_clean %>%
  select(entry, gender, rating, candy_name, country, province) %>%
  mutate(rating = recode(rating, "JOY" = 1, "MEH" = 0, "DESPAIR" = -1,))

```

```{r}

# 6. What was the most popular candy bar by this rating system for each gender in the dataset ?

recoded_candy_clean %>%
  select(entry, rating, candy_name, gender) %>%
  group_by(gender, candy_name) %>%
  drop_na(rating) %>%
  summarise(count = sum(rating)) %>%
  slice_max(count, n = 2) 

# Excluding the "any_full_sized_candy_bar" result, the results show different candy preferences by gender below.

```

```{r}

# 7.What was the most popular candy bar in each year?

year_mutated_candy_clean <- recoded_candy_clean %>%
  select(entry, rating, candy_name) %>%
  drop_na(rating) %>%
  mutate(entry = str_replace_all(string = entry,
                                 pattern = "\\_.*$",
                                 replacement = "")) %>%
  group_by(entry, candy_name) %>%
  summarise(count = sum(rating)) %>%
  slice_max(count, n = 3)

year_mutated_candy_clean

# "reese_s_peanut_butter_cups", is the most popular across all years excluding "any_full_sized_candy_bar"

```

```{r}

# 8. What was the most popular candy bar by this rating for people in US, Canada, UK, and all other countries?

recoded_candy_clean %>%
  select(candy_name, rating, country) %>%
  drop_na(rating) %>%
  filter(country == c("united states", "united kingdom", "canada")) %>%
  group_by(country, candy_name) %>%
  summarise(count = sum(rating)) %>%
  slice_max(count, n = 2)

# Canada's most popular candy is "lindt_truffle", The UK's most popular candy is "reese_s_peanut_butter_cups" and the US's most popular candy is "reese_s_peanut_butter_cups" excluding "any_full_sized_candy_bar".

```

