---
title: "Exploration of the data"
author: "Jonny Nelson"
date: "22/11/2021"
output: html_document
---

```{r}

cleaning_script_ship <- function(ship_data_by_record_id){
  ship_data_by_record_id %>%
  clean_names() %>%
  rename("latitude" = "lat", "longitude" = "long") %>%
  select(record, record_id, date, time, latitude, longitude) 
}

clean_ship_data <- cleaning_script_ship(ship_data_by_record_id)

```


```{r}
glimpse(clean_ship_data)
```

```{r}
library(stringr)
```


```{r}

cleaning_script_birds <- function(bird_data_by_record_id){
  bird_data_by_record_id %>%
  clean_names() %>%
  select(record,
         record_id,
         species_common_name_taxon_age_sex_plumage_phase,
         count) %>%
   mutate(species_common_name = 
      str_replace_all(string = species_common_name_taxon_age_sex_plumage_phase,
                      pattern = "sensu.*$|[A-Z]{2,}.*$",
                      replacement = "")) %>%
    mutate(across(where(is.character), str_trim)) %>%
    mutate(count = ifelse(is.na(count), 1, count)) %>%
    select(-species_common_name_taxon_age_sex_plumage_phase) 
}

clean_bird_data <- cleaning_script_birds(bird_data_by_record_id)
```

```{r}
glimpse(clean_bird_data)
```

```{r}
seabird_data <- left_join(clean_bird_data, clean_ship_data, "record_id")
```

```{r}

# 2. Which bird has the highest total count

seabird_data %>%
  group_by(species_common_name) %>%
  summarise(number_of_sightings = sum(count)) %>%
  arrange(desc(number_of_sightings)) %>%
  head(1,)
  

# Looked back at the regex and was able to remove any capitals letter after species common names as it may have ungrouped species
```

```{r}

# 1. Which bird has the most indivdual sightings?

seabird_data %>%
  filter(count == 1) %>%
  group_by(species_common_name) %>%
  summarise(number_of_individual_sightings = sum(count)) %>%
  arrange(desc(number_of_individual_sightings)) 

```

```{r}

# 3. Which bird had the highest total count above a latitude of -30?

seabird_data %>%
  filter(latitude > -30) %>%
  group_by(species_common_name) %>%
  summarise(number_of_sightings = sum(count)) %>%
  arrange(desc(number_of_sightings)) %>%
  head(1,)

```

```{r}

# 4. How many different types of birds were only ever seen in groups of 1?

# seabird_data %>%
#   select(species_common_name, count) %>%
#   filter(count != 1) %>%
#   group_by(species_common_name)

# function if_else statement required

# if count == 1, == TRUE
# if count >= 1, == FALSE
# if species_common_name has only TRUE = allow
# if species_common_name has TRUE and FALSE = dont allow

# species_of_1_group_only <- function(seabird_data, count) {
# 
#   if(count == 1 & count !> 1) {
#     return(species_common_name)}
#   
# }
# 
# # 
# # # if count is not equal to 1 set to 0
# # 
# species_observed_in_only_groups_of_one(seabird_data, count)

# seabird_data$count <- ifelse(seabird_data$count != 1,
#                              0,
#                              seabird_data$count)

# Needed to remove the mutate NA <- 1 out of the cleaning script and form a new script.

cleaning_script_q4 <- function(bird_data_by_record_id){
  bird_data_by_record_id %>%
  clean_names() %>%
  select(record,
         record_id,
         species_common_name_taxon_age_sex_plumage_phase,
         count) %>%
   mutate(species_common_name = 
      str_replace_all(string = species_common_name_taxon_age_sex_plumage_phase,
                      pattern = "sensu.*$|[A-Z]{2,}.*$",
                      replacement = "")) %>%
    mutate(across(where(is.character), str_trim)) %>%
    # mutate(count = ifelse(is.na(count), 1, count)) %>%
    select(-species_common_name_taxon_age_sex_plumage_phase) 
}

# the cleaning script was ran again for q4 to give the data.

clean_bird_data_q4 <- cleaning_script_q4(bird_data_by_record_id)

# The data.frames were joined again to form a special one.

seabird_data_q4 <- left_join(clean_bird_data_q4, clean_ship_data, "record_id")



groups_of_one <- seabird_data_q4 %>%
  select(species_common_name, count) %>%
  filter(count == 1) %>%
  group_by(species_common_name) %>%
  summarise(sum(count))

groups_of_greater_than_one <- seabird_data_q4 %>%
  select(species_common_name, count) %>%
  filter(count > 1) %>%
  group_by(species_common_name) %>%
  summarise(sum(count))



# Need to remove the convert NA = 1 function in cleaning script and then rejoin the tables and then run the code]=.
  
  
  
```

```{r}
# 5. How many penguins were seen?

seabird_data %>%
  filter(grepl('penguin', species_common_name)) %>%
  group_by(species_common_name) %>%
  summarise(number_of_pingos_seen = sum(count)) %>%
  arrange(desc(number_of_pingos_seen)) %>%
  mutate(total_no_pingos = sum(number_of_pingos_seen))

# Below shows the number of penguins shown per species and also the total number of penguins observed.
  

```

```{r}
glimpse(seabird_data)
```

```{r}
glimpse(clean_bird_data)
```
```{r}
glimpse(clean_ship_data)
```

